# Generated by Django 2.2 on 2020-11-01 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('visibility', models.BooleanField(default=False)),
                ('no_of_Q', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('duration', models.DurationField()),
                ('date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PackageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_student', to='packages.Package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_package', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('package', 'student')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='participants',
            field=models.ManyToManyField(through='packages.PackageStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
