# Generated by Django 2.2 on 2020-11-04 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Package Name')),
                ('description', models.TextField()),
                ('visibility', models.BooleanField(default=False, verbose_name='Package visible?')),
                ('no_of_Q', models.IntegerField(verbose_name='Total No. Of Questions')),
                ('q_visibility', models.BooleanField(default=False, help_text='click if you want to show Questions', verbose_name='Question visible?')),
                ('total_marks', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Format HH:MM:SS', verbose_name='Test Duration')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='PackageStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0, help_text='It is automatic field. please dont select it.')),
                ('submission', models.BooleanField(default=False, help_text='It is automatic field. please dont select it.', verbose_name='Submission')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_student', to='packages.Package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_package', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('package', 'student')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='participants',
            field=models.ManyToManyField(through='packages.PackageStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
