# Generated by Django 2.2 on 2020-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.DurationField(blank=True, help_text='Format HH:MM:SS', null=True, verbose_name='Test Duration'),
        ),
    ]
