# Generated by Django 2.2 on 2020-11-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_no', models.IntegerField()),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(max_length=250)),
                ('option_2', models.CharField(max_length=250)),
                ('option_3', models.CharField(max_length=250)),
                ('option_4', models.CharField(max_length=250)),
                ('correct', models.CharField(max_length=250)),
                ('marks', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_test', to='packages.Package')),
            ],
        ),
    ]
