# Generated by Django 2.2 on 2020-11-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_no', models.IntegerField(verbose_name='Question No.')),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(max_length=250)),
                ('option_2', models.CharField(max_length=250)),
                ('option_3', models.CharField(max_length=250)),
                ('option_4', models.CharField(max_length=250)),
                ('correct', models.CharField(help_text='Please Choose one option from above option', max_length=250, verbose_name='Correct Option')),
                ('marks', models.IntegerField(verbose_name='Marks on Question')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_test', to='packages.Package')),
            ],
            options={
                'ordering': ['package', 'timestamp'],
            },
        ),
    ]
